# Generated by Django 5.2.15 on 2026-06-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artikul',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dvigatel', 'Dvigatel qismlari'), ('transmissiya', 'Transmissiya'), ('gidravlika', 'Gidravlika'), ('elektr', 'Elektr jihozlar'), ('sovitish', 'Sovitish tizimi'), ('zapchast', "Qo'shimcha")], default='zapchast', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
