# Generated by Django 5.2.15 on 2026-06-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_product_artikul_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artikul',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
    ]
